name: connect_plus_student
description: A new Flutter project.



publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  flutterfire_ui: ^0.4.3+20
  google_sign_in: ^5.4.3
  firebase_auth: ^4.2.5
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.3
  country_picker: ^2.0.19
  circular_bottom_navigation: ^2.3.0
  firebase_database: ^10.0.9
  cloud_firestore: ^4.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  assets:
    - Assets/login.png
    - Assets/connect-student-logo.png
    - Assets/connect-student-logo-removebg-preview.png
    - Assets/confirmation.jpg
  

  
  

  
  

  
  
  
  
  




  
  
  
  
  
  
  
  
